spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver #冒号后面要有空格，下同
    url: jdbc:mysql://localhost:3306/gxstwm?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  mvc:
    static-path-pattern: /static/** #静态资源映射路径
  thymeleaf:
    prefix: classpath:/templates/
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.jiangxiacollege.canteenwebsite.admin.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印SQL日志，便于调试
upload: C:/upload/ #自定义文件上传路径